server:
  # 基本配置
  address: ":8002"
  serverRoot: "public"
  serverAgent: "Go HTTP Server"

  # Cookie配置
  cookieMaxAge: "365d" # Cookie有效期。默认为365天
  cookiePath: "/"      # Cookie有效路径。默认为"/"表示全站所有路径下有效
  cookieDomain: ""     # Cookie有效域名。默认为当前配置Cookie时的域名

  # Sessions配置
  sessionMaxAge: "24h"            # Session有效期
  sessionIdName: "SESS_ID"        # SessionId的键名名称
  sessionCookieOutput: true       # Session特性开启时，是否将SessionId返回到Cookie中
  sessionPath: "runtime/sessions" # Session存储的文件目录路径

  # 日志扩展配置(参数日志组件配置)
  logger:
    # path: "runtime/logs/" # 日志文件路径。默认为空，表示关闭，仅输出到终端
    level: "all"
    stdout: true

  # 接口文档
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Database配置
database:
  default:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/db"
    charset: "utf8"
    debug: "true"
